config/routes.rb
Rails.application.routes.draw do

  root "recipes#index"
  resources :recipes
  resources :users, except: [:new]

  get "/signup", to: "users#new"
  get "/login", to: "sessions#new"
  get "/logout", to: "sessions#destroy"
  resources :sessions, only: [:create]

end


#      Prefix Verb   URI Pattern                 Controller#Action
#        root GET    /                           recipes#index
#     recipes GET    /recipes(.:format)          recipes#index
#             POST   /recipes(.:format)          recipes#create
#  new_recipe GET    /recipes/new(.:format)      recipes#new
# edit_recipe GET    /recipes/:id/edit(.:format) recipes#edit
#      recipe GET    /recipes/:id(.:format)      recipes#show
#             PATCH  /recipes/:id(.:format)      recipes#update
#             PUT    /recipes/:id(.:format)      recipes#update
#             DELETE /recipes/:id(.:format)      recipes#destroy
#       users GET    /users(.:format)            users#index
#             POST   /users(.:format)            users#create
#   edit_user GET    /users/:id/edit(.:format)   users#edit
#        user GET    /users/:id(.:format)        users#show
#             PATCH  /users/:id(.:format)        users#update
#             PUT    /users/:id(.:format)        users#update
#             DELETE /users/:id(.:format)        users#destroy
#      signup GET    /signup(.:format)           users#new
#       login GET    /login(.:format)            sessions#new
#      logout GET    /logout(.:format)           sessions#destroy
#    sessions POST   /sessions(.:format)         sessions#create

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :user

  validates :name, presence: true, length: { minimum: 3 }
  validates :instructions, presence: true, length: { minimum: 10 }

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :recipes, dependent: :destroy

  # note: has_secure_password automatically adds validations for presence
  # of password, password length < 72 characters, and password_confirmation
  has_secure_password

  # only validate password length on create (not update)
  validates :password, length: { minimum: 6 }, on: :create

  validates :email,
    presence: true,
    uniqueness: true,
    format: {
      with: /@/,
      message: "not a valid format"
    }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  helper_method :current_user

  def authorize
    redirect_to login_path unless current_user
  end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_filter :set_recipe, except: [:index, :new, :create]
  before_filter :authorize, except: [:index, :show]

  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = current_user.recipes.new(recipe_params)
    if @recipe.save
      flash[:notice] = "Successfully created recipe."
      redirect_to recipe_path(@recipe)
    else
      flash[:error] = @recipe.errors.full_messages.join(", ")
      redirect_to new_recipe_path
    end
  end

  def show
  end

  def edit
    # don't let current_user see another user's recipe edit view
    unless current_user == @recipe.user
      redirect_to user_path(current_user)
    end
  end

  def update
    # only let current_user update their own recipes
    if current_user == @recipe.user
      if @recipe.update_attributes(recipe_params)
        flash[:notice] = "Successfully updated recipe."
        redirect_to recipe_path(@recipe)
      else
        flash[:error] = @recipe.errors.full_messages.join(", ")
        redirect_to edit_recipe_path(@recipe)
      end
    else
      redirect_to user_path(current_user)
    end
  end

  def destroy
    # only let current_user delete their own recipes
    if current_user == @recipe.user
      @recipe.destroy
      flash[:notice] = "Successfully deleted recipe."
    end
    redirect_to user_path(current_user)
  end

  private

    def recipe_params
      params.require(:recipe).permit(:name, :instructions)
    end

    def set_recipe
      recipe_id = params[:id]
      @recipe = Recipe.find_by_id(recipe_id)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    # don't let current_user see the log in view
    if current_user
      redirect_to user_path(current_user)
    end
  end

  def create
    @user = User.find_by_email(user_params[:email])
    # If the user exists AND the password entered is correct.
    if @user && @user.authenticate(user_params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user 
      # logged in when they navigate around our website.
      session[:user_id] = @user.id
      flash[:notice] = "Successfully logged in."
      redirect_to user_path(@user)
    else
      flash[:error] = "Incorrect email or password."
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Successfully logged out."
    redirect_to root_path
  end

  private

    def user_params
      params.require(:user).permit(:email, :password)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :set_user, except: [:index, :new, :create]
  before_filter :authorize, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def new
    # don't let current_user see the sign up view
    if current_user
      redirect_to user_path(current_user)
    else
      @user = User.new
    end
  end

  def create
    # don't let current_user create new account
    if current_user
      redirect_to user_path(current_user)
    else
      @user = User.new(user_params)
      if @user.save
        session[:user_id] = @user.id
        flash[:notice] = "Successfully signed up."
        redirect_to user_path(@user)
      else
        flash[:error] = @user.errors.full_messages.join(", ")
        redirect_to signup_path
      end
    end
  end

  def show
  end

  def edit
    # don't let current_user see another user's edit view
    unless current_user == @user
      redirect_to user_path(current_user)
    end
  end

  def update
    # only let current_user update their own account
    if current_user == @user
      if @user.update_attributes(user_params)
        flash[:notice] = "Successfully updated profile."
        redirect_to user_path(@user)
      else
        flash[:error] = @user.errors.full_messages.join(", ")
        redirect_to edit_user_path(@user)
      end
    else
      redirect_to user_path(current_user)
    end
  end

  def destroy
    # only let current_user delete their own account
    if current_user == @user
      @user.destroy
      session[:user_id] = nil
      flash[:notice] = "Successfully deleted profile."
      redirect_to root_path
    else
      redirect_to user_path(current_user)
    end
  end

  private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end

    def set_user
      user_id = params[:id]
      @user = User.find_by_id(user_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- application stylesheet -->
  <%= stylesheet_link_tag :application, media: :all %>

  <title>RailsPartialsHelpers</title>
</head>
<body>
  <%= render "shared/navbar" %>
  <% flash.each do |name, msg| %>
    <div class="alert <%= name == 'error' ? 'alert-danger' : 'alert-info' %>">
      <div class="container">
        <%= msg %>
      </div>
    </div>
  <% end %>
  <div class="container site-content">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= yield %>
      </div>
    </div>
  </div>
  
  <!-- application javascript file -->
  <%= javascript_include_tag :application %>
</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: "Recipe name", class: "form-control", autofocus: true %>
  </div>
  <div class="form-group">
    <%= f.label :instructions %>
    <%= f.text_area :instructions, placeholder: "Type your recipe instructions here", class: "form-control" %>
  </div>
  <%= f.submit "Save Recipe", class: "btn btn-block btn-default" %>
<% end %>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>
<hr>
<%= render "form" %>

app/views/recipes/index.html.erb
<h1>Recipe Book</h1>
<hr>
<% @recipes.each do |recipe| %>
  <strong><%= recipe.name %></strong> - <%= link_to "View Recipe", recipe_path(recipe) %>
  <hr>
<% end %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>
<hr>
<%= render "form" %>

app/views/recipes/show.html.erb
<h1><%= @recipe.name %></h1>
<hr>
<p><%= @recipe.instructions %></p>
<p class="small text-muted">
  Posted <%= time_ago_in_words(@recipe.created_at) %> ago by <%= link_to @recipe.user.email, user_path(@recipe.user) %>
</p>

<!-- only let user who wrote the recipe see edit/delete buttons -->
<% if current_user && current_user == @recipe.user %>
  <hr>
  <p>
    <%= link_to "Edit Recipe", edit_recipe_path(@recipe), class: "btn btn-default" %>
    <%= link_to "Delete Recipe", recipe_path(@recipe), method: :delete, class: "btn btn-default" %>
  </p>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "RailsPartialsHelpers", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "All Recipes", recipes_path %></li>
        <li><%= link_to "All Users", users_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to "+ New Recipe", new_recipe_path %></li>
          <li><%= link_to "Profile", user_path(current_user) %></li>
          <li><%= link_to "Log Out", logout_path %></li>
        <% else %>
          <li><%= link_to "Sign Up", signup_path %></li>
          <li><%= link_to "Log In", login_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>
<hr>
<%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, placeholder: "email@example.com", class: "form-control", autofocus: true %>
  </div>
  <%= f.submit "Save Profile", class: "btn btn-block btn-default" %>
<% end %>

app/views/users/index.html.erb
<h1>All Users</h1>
<hr>
<% @users.each do |user| %>
  <%= user.email %> - <%= link_to "View Profile", user_path(user) %>
  <hr>
<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<hr>

<%= form_for @user do |f| %>
<div class="form-group">
  <%= f.text_field :email, class: "form-control", placeholder: "name", autofocus: true %>
  <%= f.password_field :password, class: "form-control", placeholder: "password" %>
  <%= f.password_field :password_confirmation, class: "form-control", placeholder: "password confirm" %>
  <%= f.submit "Sign-up!", class: "btn btn-block btn-primary" %>
</div>
<% end %>

<hr>








<!-- <form action="/users" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <div class="form-group">
    <label for="user_email">Email</label>
    <input type="text" name="user[email]" class="form-control" id="user_email" placeholder="email@example.com" autofocus>
  </div>
  <div class="form-group">
    <label for="user_password">Password</label>
    <input type="password" name="user[password]" class="form-control" id="user_password" placeholder="Must be at least 6 characters">
  </div>
  <div class="form-group">
    <label for="user_password_confirmation">Password Confirmation</label>
    <input type="password" name="user[password_confirmation]" class="form-control" id="user_password_confirmation" placeholder="Confirm password">
  </div>
  <input type="submit" value="Sign Up" class="btn btn-block btn-default">
</form>
<br> -->
<p>Already have an account? <a href="/login">Click here</a> to log in.</p>

app/views/users/show.html.erb
<h1>User Profile</h1>
<hr>
<p><strong>Email:</strong> <%= @user.email %></p>
<p class="small text-muted">Joined <%= time_ago_in_words(@user.created_at) %> ago</p>

<!-- only let user who owns this account see edit/delete buttons -->
<% if current_user && current_user == @user %>
  <hr>
  <p>
    <%= link_to "Edit Profile", edit_user_path(@user), class: "btn btn-default" %>
    <%= link_to "Delete Profile", user_path(@user), method: :delete, class: "btn btn-default" %>
  </p>
<% end %>

<% if @user.recipes.any? %>
  <br>
  <h4>User's Recipes</h4>
  <hr>
  <% @user.recipes.each do |recipe| %>
    <strong><%= recipe.name %></strong> - <%= link_to "View Recipe", recipe_path(recipe) %>
    <hr>
  <% end %>
<% end %>